name: "units-test"
on:
  pull_request:
    branches: [ master ]

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        mappingFile: 'mapping.json'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
